---
name: Test

on:
  workflow_call:

permissions: {}

jobs:
  test-simple:
    name: Test Simple
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Test
        uses: "./"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-pull-request:
    name: Test Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    needs:
      - test-simple
    if: ${{ github.event_name == 'pull_request' }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - terramate-args: "--changed"
            comment-pull-request: "true"
          - terramate-args: ""
            comment-pull-request: "false"
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Test
        uses: "./"
        with:
          terramate-args: ${{ matrix.terramate-args }}
          comment-pull-request: ${{ matrix.comment-pull-request }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-setup:
    name: Test Setup
    runs-on: ubuntu-latest
    needs:
      - test-simple
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: pinned versions
            terramate-version: "0.4.2"
            terraform-version: "1.5.7"
            terraform-plan-file: "out.tfplan"
            tmp-file: "tmp.txt"
            cleanup: "true"
          - name: latest versions with custom paths
            terramate-version: "latest"
            terraform-version: "latest"
            terraform-plan-file: "plan.out"
            tmp-file: "file.tmp"
            cleanup: "false"
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Test
        uses: "./"
        with:
          terramate-version: ${{ matrix.terramate-version }}
          terraform-version: ${{ matrix.terraform-version }}
          terraform-plan-file: ${{ matrix.terraform-plan-file }}
          temp-file: ${{ matrix.tmp-file }}
          cleanup: ${{ matrix.cleanup }}
          comment-pull-request: false

  test-jobs:
    name: Test Jobs
    runs-on: ubuntu-latest
    needs:
      - test-setup
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: all enabled
            lint: "true"
            validate: "true"
            plan: "true"
            apply: "true"
            destroy: "true"
          - name: all disabled
            lint: "false"
            validate: "false"
            plan: "false"
            apply: "false"
            destroy: "false"
          - name: plan and apply only
            lint: "false"
            validate: "false"
            plan: "true"
            apply: "true"
            destroy: "false"
          - name: destroy only
            lint: "false"
            validate: "false"
            plan: "false"
            apply: "false"
            destroy: "true"
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Test With Setup And Init
        uses: "./"
        with:
          lint: ${{ matrix.lint }}
          validate: ${{ matrix.validate }}
          plan: ${{ matrix.plan }}
          apply: ${{ matrix.apply }}
          destroy: ${{ matrix.destroy }}
          comment-pull-request: false

      # jscpd:ignore-start
      - name: Test With Init Only
        uses: "./"
        with:
          setup: false
          init: true
          lint: ${{ matrix.lint }}
          validate: ${{ matrix.validate }}
          plan: ${{ matrix.plan }}
          apply: ${{ matrix.apply }}
          destroy: ${{ matrix.destroy }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-pull-request: false

      - name: Test Without Setup And Init
        uses: "./"
        with:
          setup: false
          init: false
          lint: ${{ matrix.lint }}
          validate: ${{ matrix.validate }}
          plan: ${{ matrix.plan }}
          apply: ${{ matrix.apply }}
          destroy: ${{ matrix.destroy }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-pull-request: false
      # jscpd:ignore-end

  test-terraform-args:
    name: Test Terraform Arguments
    runs-on: ubuntu-latest
    needs:
      - test-jobs
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: all args set
            terraform-common-args: "-no-color"
            terraform-init-args: "-upgrade"
            terraform-validate-args: "-json"
            terraform-plan-args: "-parallelism=3"
            terraform-show-args: "-no-color"
            terraform-apply-args: "-parallelism=2"
            terraform-destroy-args: "-compact-warnings"
          - name: no args (defaults)
            terraform-common-args: ""
            terraform-init-args: ""
            terraform-validate-args: ""
            terraform-plan-args: ""
            terraform-show-args: ""
            terraform-apply-args: ""
            terraform-destroy-args: ""
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Test
        uses: "./"
        with:
          terraform-common-args: ${{ matrix.terraform-common-args }}
          terraform-init-args: ${{ matrix.terraform-init-args }}
          terraform-validate-args: ${{ matrix.terraform-validate-args }}
          terraform-plan-args: ${{ matrix.terraform-plan-args }}
          terraform-show-args: ${{ matrix.terraform-show-args }}
          terraform-apply-args: ${{ matrix.terraform-apply-args }}
          terraform-destroy-args: ${{ matrix.terraform-destroy-args }}
          apply: true
          destroy: true
          comment-pull-request: false

  test-terramate-args:
    name: Test Terramate Arguments
    runs-on: ubuntu-latest
    needs:
      - test-terraform-args
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: all args set
            terramate-args: "--changed"
            terramate-plan-args: "--quiet"
            terramate-apply-args: "--quiet"
            terramate-destroy-args: "--reverse"
          - name: no args (defaults)
            terramate-args: ""
            terramate-plan-args: ""
            terramate-apply-args: ""
            terramate-destroy-args: ""
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Test
        uses: "./"
        with:
          terramate-args: ${{ matrix.terramate-args }}
          terramate-plan-args: ${{ matrix.terramate-plan-args }}
          terramate-apply-args: ${{ matrix.terramate-apply-args }}
          terramate-destroy-args: ${{ matrix.terramate-destroy-args }}
          apply: true
          destroy: true
          comment-pull-request: false
